Make update_or_create_address null-safe
This is causing a KeyError, e.g.

File "/app/parking_permits/admin_resolvers.py", line 334, in update_or_create_address
if address_info["street_name_sv"]
KeyError: 'street_name_sv'
ERROR:ariadne:'street_name_sv'